Updates for required collection
Just tried the CLI and it looks like 'collection' is now required for all operations:

```
$ stac-api-validator --root-url https://tamn.snapplanet.io/ \
    --conformance core
Usage: stac-api-validator [OPTIONS]
Try 'stac-api-validator --help' for help.

Error: Missing option '--collection'.
```

So updated the docs to reflect that.

If it is not supposed to be required for like just testing core then feel free to drop this PR.